[versions]
coilNetworkKtor3 = "3.0.4"
coilVersion = "3.0.4"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.25"
compose = "1.7.0"
compose-tooling = "1.6.8"
agp = "8.5.2"

sqlDelight = "2.0.2"
sqlite = "2.5.0-alpha07"

android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"

# Koin
koin = "4.1.0-Beta1"
koin-compose = "4.1.0-Beta1"
koin-annotations = "2.0.0-Beta2"
stately = "2.0.7"

# Settings
multiplatform-settings = "1.1.1"

androidx-activityCompose = "1.9.1"
androidx-appcompat = "1.7.0"
androidx-core-ktx = "1.13.1"

softylines-plugin = "0.1.0"

voyager = "1.0.0"

ktor3 ="3.0.3"
logback = "1.5.6"

uuid = "0.8.4"

kotlinx-coroutines = "1.9.0-RC"
kotlinx-serialization-json = "1.7.0-RC"
kotlinx-datetime = "0.6.0"
kotlinx-kover = "0.7.4"

coil = "3.0.0-alpha10"

calf = "0.5.3"

buildkonfig = "0.15.1"

konsist = "0.13.0"

sentry = "0.4.0"

ktlint = "12.1.1"

ktlint-compose-rules = "0.4.10"

firebaseCrashlyticsBuildtools = "3.0.2"

androidx-room = "2.7.0-alpha01"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
material = "1.12.0"

[libraries]
coil = { module = "io.coil-kt.coil3:coil", version.ref = "coilVersion" }
coil3-coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coilNetworkKtor3" }
gradlePlugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
gradlePlugin-jetbrainsCompose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-composeCompiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
gradlePlugin-seriazliation = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-tooling" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-coreJs = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-js", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }

# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Voyager
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor3" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor3" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor3" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor3" }
ktor-engine-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor3" }
ktor-engine-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor3" }
ktor-engine-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor3" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor3" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor3" }

# Room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Coil
coil-core = { module = "io.coil-kt.coil3:coil-core", version = "3.0.4" }
coil-network = { module = "io.coil-kt.coil3:coil-network", version = "3.0.4" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version = "3.0.4" }

# Calf
calf-ui = { module = "com.mohamedrejeb.calf:calf-ui", version.ref = "calf" }
calf-permissions = { module = "com.mohamedrejeb.calf:calf-permissions", version.ref = "calf" }
calf-filepicker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf" }

# UUID
uuid = { module = "com.benasher44:uuid", version.ref = "uuid" }

# Konsist
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }

# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
extras-stately = { module = "co.touchlab:stately-common", version.ref = "stately" }
#extras-stately-collections = { module = "co.touchlab:stately-concurrent-collections", version.ref = "stately" }

# Multiplatform Settings
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

# SQLDelight
sqldelight-coroutinesExtensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight_sqliteDialect = { module = "app.cash.sqldelight:sqlite-3-24-dialect", version.ref = "sqlDelight" }
sqldelight-primitiveAdapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqlDelight" }
sqldelight-runtime = { module = "app.cash.sqldelight:runtime", version.ref = "sqlDelight" }
sqldelight-sqliteDriver = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqldelight-driver-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqlDelight" }
sqldelight-driver-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

# Ktlint
ktlint-compose-rules = { module = "io.nlopez.compose.rules:ktlint", version.ref = "ktlint-compose-rules" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
softylines = { id = "com.softylines.gradle.setup", version.ref = "softylines-plugin" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
room = { id = "androidx.room", version.ref = "androidx-room" }

[bundles]

koin = [
    "koin-core",
    "koin-annotations",
]

ktor = [
    "ktor-content-negotiation",
    "ktor-client-core",
    "ktor-serialization-json",
    "ktor-client-serialization",
    "ktor-logging",
    "ktor-client-auth"
]


